server:
  port: 8201
spring:
  application:
    name: service-hosp
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: misakimei
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  cloud:
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858 #设置sentinel地址
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #nacos地址
#  data:
#    mongodb:
#      host: 192.168.44.163
#      port: 27017
#      database: yygh_hosp
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

mybatis-plus:
  mapper-locations: classpath:com/sanguo/yygh/mapper/xml/*.xml

feign:
  sentinel:
    enabled: true #开启sentinel


